### ISSUE TITLE
Transfer Sponsorship Prospectus to markdown

### ISSUE THREAD

**Issue by JJ11teen** [adelaideblockchain/internal-meetings#3]
The Sponsorship Prospectus should be transferred out of a .docx and into an .md file. This will allow native viewing in GitHub, mobile support, and line by line revision history.

Helpful cheat sheet for writing markdown: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by paulpounendis** [comment]
No worries, will read up on it now.

**Comment by JJ11teen** [comment]
Markdown to pdf is a very common requirement! However if pdf is the end goal I'd recommend using latex instead.

**Comment by paulpounendis** [comment]
Thanks for the recommendation. Ill close this issue now.
